services:
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3030:80"
    environment:
      - NODE_ENV=development
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    restart: unless-stopped

  frontend-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    profiles:
      - production
